version: '3'
services:
  namenode:
    build: .
    command: hdfs namenode
    ports:
      - 8020:8020
      - 50070:50070  # NameNode
      - 5556:5556
    environment:
      - HADOOP_OPTS=-javaagent:/opt/jmx_prometheus_javaagent/jmx_prometheus_javaagent.jar=5556:/opt/jmx_prometheus_javaagent/config.yml
    volumes:
      - "./tmp/namenode:/hadoop/dfs/name"
      - "./config:/etc/hadoop:ro"
      - "./config/jmx-namenode-config.yml:/opt/jmx_prometheus_javaagent/config.yml"
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail http://localhost:50070/ || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 5
  datanode-1:
    build: .
    command: hdfs datanode
    ports:
      - 5557:5556
    environment:
      - HADOOP_OPTS=-javaagent:/opt/jmx_prometheus_javaagent/jmx_prometheus_javaagent.jar=5556:/opt/jmx_prometheus_javaagent/config.yml
    depends_on:
      namenode:
        condition: service_healthy
    volumes:
      - "./tmp/datanode-1:/hadoop/dfs/data"
      - "./config:/etc/hadoop:ro"
      - "./config/jmx-datanode-config.yml:/opt/jmx_prometheus_javaagent/config.yml"
  datanode-2:
    build: .
    command: hdfs datanode
    ports:
      - 5558:5556
    environment:
      - HADOOP_OPTS=-javaagent:/opt/jmx_prometheus_javaagent/jmx_prometheus_javaagent.jar=5556:/opt/jmx_prometheus_javaagent/config.yml
    depends_on:
      namenode:
        condition: service_healthy
    volumes:
      - "./tmp/datanode-2:/hadoop/dfs/data"
      - "./config:/etc/hadoop:ro"
      - "./config/jmx-datanode-config.yml:/opt/jmx_prometheus_javaagent/config.yml"
